//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }

        [DisplayName("Mã Sản Phẩm")]    
        public int MaSP { get; set; }

        [DisplayName("Tên Sản Phẩm")]
        public string TenSP { get; set; }

        [DisplayName("Đơn Giá")]
        public Nullable<decimal> DonGia { get; set; }

        [DisplayName("Ngày Cập Nhật")]
        public Nullable<System.DateTime> NgayCapNhap { get; set; }

        [DisplayName("Cấu Hình")]
        public string CauHinh { get; set; }

        [DisplayName("Mô Tả")]
        public string MoTa { get; set; }

        [DisplayName("Hình Ảnh")]
        public string HinhAnh { get; set; }

        [DisplayName("Số Lượng Tồn")]
        public Nullable<int> SoLuongTon { get; set; }

        [DisplayName("Mới")]
        public Nullable<int> Moi { get; set; }

        [DisplayName("Mã Nhà Cung Cấp")]
        public Nullable<int> MaNCC { get; set; }

        [DisplayName("Mã Nhà Sản Xuất")]
        public Nullable<int> MaNSX { get; set; }

        [DisplayName("Mã Loại Sản Phẩm")]
        public Nullable<int> MaLoaiSP { get; set; }

        [DisplayName("Đã Xóa")]
        public Nullable<bool> DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
